export const OPENSOURCE_CONTRIBUTIONS = [
  {
    org: "microsoft",
    repo: "fluentui",
    prUrl: "https://github.com/microsoft/fluentui/pull/19207",
    date: "31 Jul 2021",
    title: "fix: fixed broken links",
    prId: 19207,
  },
  {
    org: "microsoft",
    repo: "fluentui",
    prUrl: "https://github.com/microsoft/fluentui/pull/19208",
    date: "31 Jul 2021",
    title: "fix: ios broken links",
    prId: 19208,
  },
  {
    org: "microsoft",
    repo: "fluentui",
    prUrl: "https://github.com/microsoft/fluentui/pull/20077",
    date: "5 Oct 2021",
    title: "feat: added pointer cursor for feedback link",
    prId: 20077,
  },
  {
    org: "microsoft",
    repo: "playwright",
    prUrl: "https://github.com/microsoft/playwright/pull/13094",
    date: "6 Apr 2022",
    title: "fix: fixes typo",
    prId: 13094,
  },
  {
    org: "vuejs",
    repo: "v2.vuejs.org",
    prUrl: "https://github.com/vuejs/v2.vuejs.org/pull/2848",
    date: "1 Aug 2021",
    title: "feat: added cursor pointer for subscribe button",
    prId: 2848,
  },
  {
    org: "vuejs",
    repo: "docs",
    prUrl: "https://github.com/vuejs/docs/pull/1149",
    date: "26 Jul 2021",
    title: "feat: added cursor pointer to ensure consistency",
    prId: 1149,
  },
  {
    org: "facebook",
    repo: "react-native-website",
    prUrl: "https://github.com/facebook/react-native-website/pull/2705",
    date: "29 Jul 2021",
    title: "docs: typo correction",
    prId: 2705,
  },
].sort((a, b) => new Date(b.date) - new Date(a.date));
