name: Lighthouse CI
on: [push]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Waiting for Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.2.0
        id: waitVercelPreview
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 60
      - run: echo ${{steps.waitVercelPreview.outputs.url}}

      # - name: Lighthouse
      #   uses: treosh/lighthouse-ci-action@v8
      #   with:
      #     configPath: './lighthouserc.json'
      #     uploadArtifacts: true
      #     temporaryPublicStorage: true
