name: Lighthouse CI
on: [push]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Waiting for Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.2.0
        id: vercelPreview
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          check_interval: 10
          max_timeout: 180
      - run: echo ${{steps.vercelPreview.outputs.url}}

      - name: Lighthouse
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: ${{steps.vercelPreview.outputs.url}}
          configPath: "./lighthouserc.json"
          uploadArtifacts: true
          temporaryPublicStorage: true
