name: Lighthouse CI
on: [push]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Lighthouse
          uses: treosh/lighthouse-ci-action@v8
          with:
            uploadArtifacts: true 
            temporaryPublicStorage: true
